config/routes.rb
Rails.application.routes.draw do
  resources :cocktails do
    resources :doses, only:[:new, :create]
  end
  resources :doses, only: :destroy

  root 'cocktails#index'

end

app/models/cocktail.rb
class Cocktail < ActiveRecord::Base
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  validates :name, presence: true, uniqueness: true
end

app/models/dose.rb
class Dose < ActiveRecord::Base
  belongs_to :cocktail
  belongs_to :ingredient
  validates :description, :cocktail_id, :ingredient_id, presence: true
  validates :cocktail_id, uniqueness: {scope: :ingredient_id}
end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  has_many :doses
  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  def index
    @cocktails = Cocktail.all
  end

  def show
    @cocktail = Cocktail.find(params[:id])
  end

  def new
    @cocktail = Cocktail.new
  end

 def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
    redirect_to cocktail_path(@cocktail)
    else
    render :new
    end
  end

   protected

  def cocktail_params
    params.require(:cocktail).permit(:name)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController

  before_action :find_cocktail, only: [:new, :create]
  before_action :find_dose, only: [:destroy]
  def new
    @dose = Dose.new
  end

  def create
  @dose = Dose.new(dose_params)
    if @dose.save
    redirect_to cocktail_path(@cocktail)
    else
    render :new
    end
  end

  def destroy
    @dose.destroy
    redirect_to cocktail_path
  end

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id, :cocktail_id)
  end

  def find_cocktail
    @cocktail = Cocktail.find(params[:cocktail_id])
  end

  def find_dose
    @dose = Dose.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/create.html.erb
<h1>Cocktails#create</h1>
<p>Find me in app/views/cocktails/create.html.erb</p>

app/views/cocktails/index.html.erb
<div class="text-center">
  <h1>Cocktails</h1>
  <div class="container">
    <% @cocktails.each do |cocktail| %>
      <div class="row">
        <div class="col-md-4 col-md-offset-4">
          <h3><%= cocktail.name %></h3>
        </div>
      </div>
      <div class="row">
        <div class="col-sm-12"></div>
        <%= link_to "See details", cocktail_path(cocktail.id), class: "btn btn-primary"%>
        <br>
        <br>
      </div>
    <% end %>
  </div>
  <p><%= link_to "Add a New Cocktail", new_cocktail_path, class: "btn btn-primary"%></p>
</div>

app/views/cocktails/new.html.erb
<div class="text-center">
  <h1>New Cocktail</h1>
  <br>
  <div class="container">
    <div class="row">
      <div class="col-md-4 col-md-offset-4">
        <%= simple_form_for @cocktail do |f| %>
          <%= f.error_notification %>
          <%= f.input :name %>
          <%= f.submit "Post", class: "btn btn-primary" %>
        <% end %>
        <%= link_to("Back to Cocktail List", cocktails_path) %>
      </div>
    </div>
  </div>
</div>

app/views/cocktails/show.html.erb
<div class="text-center">
  <h1><%= @cocktail.name %></h1>
  <p>-------------</p>
  <div class="container">
    <div class="row">
      <div class="col-md-4 col-md-offset-4">
        <ul>
          <%= render @doses %>
        </ul>
        <section>
          <%= render 'shared/dose_form' %>
        </section>
        <br>
        <p><%= link_to("Back to Cocktail List", cocktails_path) %></p>
      </div>
    </div>
  </div>
</div>

app/views/doses/_dose.html.erb
<li id="review-<%= dose.id %>" class="text-left">
  <span><%= @dose.description %></span>
  <span><% @ingredient = Ingredient.find(dose.ingredient_id) %></span>
  <span><%= @ingredient.name %></span>
  <span><%= link_to("Remove ingredient", cocktail_dose_path(@cocktail, dose), method: :delete) %></span>
</li>

app/views/doses/create.html.erb
<h1>Doses#create</h1>
<p>Find me in app/views/doses/create.html.erb</p>

app/views/doses/destroy.html.erb
<h1>Doses#destroy</h1>
<p>Find me in app/views/doses/destroy.html.erb</p>

app/views/doses/new.html.erb
<h1>Doses#new</h1>
<p>Add a dose for a selected cocktail</p>

<%= simple_form_for [@cocktail, @dose] do |f| %>
  <%= f.error_notification %>
  <%= f.input :description %>
  <%= f.input :ingredient_id, collection: @ingredients_collection %>
  <%= f.button :submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MisterCocktail</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
</head>
<body>

<%= yield %>

</body>
</html>